### ISSUE TITLE
Improve templates API

### ISSUE THREAD

**Issue by baktun14** [akash-network/console#102]
- The templates API are getting heavy as more templates are added to the awesome akash repo. Also, the endpoint is called many times throughout the UX.
![image](https://github.com/akash-network/cloudmos/assets/15185355/93273c75-f2d2-4b33-a5e9-31cd4b3ef42f)
---
TODO
- [x] Modifiy the [templates list api endpoint](https://github.com/akash-network/console/blob/main/apps/api/src/routes/v1/templates.ts#L44) to only return the info needed to display in a list (without the readme, etc) with goal to reduce the amount of uncessary data sent to the browser
- [x] Add a new api endpoint for a template detail with all the info

**Comment by anilmurty** [comment]
As an additional input - this inefficient data loading also causes issues in loading the docker container list in the "rent a GPU" page.

That said, this isn't necessarily a huge UX issue at the moment

**Comment by stalniy** [comment]
Hi @baktun14 

I'm having a hard time to setup the project. Default config doesn't work. It wants me to provide some database urls. I spent ~3h trying to break through different configuration errors without success, so I need somebodies' help to spin up the console and its dependencies.

However I've already finished an implementation looking at how everything works on production but I can't test it.

**Comment by baktun14** [comment]
Sorry if you had issues with the local setup, we're gonna improve this for sure. I can support you in a couple hours or @ygrishajev will before that.

**Comment by baktun14** [comment]
@stalniy You can create your PR and we'll fix it if you're still having issues with your local setup.

**Comment by stalniy** [comment]
@baktun14, I created PR. Thanks to @ygrishajev I was able to run it locally and test that it actually works according to requirements. 

However it's quite hard to test this functionality because of few reasons:
* services have hard dependencies which cannot be substituted in runtime as a result it's hard to write unit test without either pure hacks or jest hacks (mocking Nodejs modules in `__mock__` folder)
* writing e2e API tests is also a bad idea in this case because this functionality depends on 3rd party (Github) and if 3rd party is down or rate limit requests then these tests will fail, potentially stoping deployment and delivering business critical fix to production. 

IMO better choice in this case would be to have some unit tests with jest manual mocks because then we at least do not depend on 3rd party availability. But the ideal case would be to re-write those services to classes or factory functions, to make them accept their dependencies, so then dependencies can be substituted during unit testing (this can be done via some DI library like tsyringe or just simple DIC entry point with manual object instantiation, this works fine if amount of services is low). But this is completely different task

**Comment by baktun14** [comment]
Thanks for your valuable input and suggestions @stalniy 

There are definitely better ways to implement this for testing. Like every project, we have some technical debt that we slowly update over time and we actually implemented DI for some of the endpoints, mainly the new ones.

I left [a comment](https://github.com/akash-network/console/pull/481#issuecomment-2484126824) suggesting minor changes for this issue to be completed and not go too out of scope.
