### ISSUE TITLE
[FEATURE REQUEST] Add Provider Attribute to show support for SSL/TLS Wildcard Certs

### ISSUE THREAD

**Issue by ourlink** [akash-network/console#201]
In the list of Provider Attributes, offered through Cloudmos, currently, there does not exist any attribute to show that a Provider has deployed a WildCard SSL/TLS Certificate via LetsEncrypt. However, any provider can add SSL/TLS Certificates following the TLS Certs for Akash Provider (Optional Step) in the Akash Network Docs. ( https://akash.network/docs/providers/build-a-cloud-provider/tls-certs-for-akash-provider/ )

This feature request is for the Cloudmos team to add a set of attributes to display on the Provider Overview page highlighting the offering of SSL/TLS with any web deployment. 

The request is to display **SSL/TLS Offered=Y** similar to how the attributes for Persistent Storage, IP Leases, and Custom Domain are displayed.

**Comment by baktun14** [comment]
We can add a field in the Provider attribute form that makes it easy for provider to edit, but otherwise this is out of our control since it's up to the providers to set this attribute. Please create an issue under the [support repo](https://github.com/akash-network/support/issues).

Related to (https://github.com/akash-network/cloudmos/issues/194)
