### ISSUE TITLE
Replace akashnet.net rpc with proxy

### ISSUE THREAD

**Issue by baktun14** [akash-network/console#263]
We're depedent on this node to run 100% of the time for the api and other places in the code. We need to replace it with the new [RPC proxy](https://github.com/akash-network/support/issues/235) that will be built,

**Comment by nick134-bit** [comment]
Hey @troian and @baktun14 ,

Public endpoints tend to enforce rate limits per IP address. As far as I know, using a proxy server would result in all users sharing the same rate limits if no caching is in place. Due to this, I recently created a REST API endpoint for another frontend that checks the health of public RPCs/RESTs and provides an updated list. Putting the RPC selection on the client side would ensure availability even if usage of the endpoints increases significantly. 

You can check it out here: https://9c0pbpbijhepr6ijm4lk85uiuc.ingress.europlots.com/api/rpcs/akash

**Comment by baktun14** [comment]
Hey, we currently have client side rpc selection. This is mostly for our api that relies on the akashnet.net rpc and we need a proxy for reliability. Thanks for the list of rpcs.
